spring.application.name=springai-chat-predict
server.port=8081
#for google genai model
# spring.ai.google.genai.chat.model=gemini-2.5-flash
# spring.ai.google.genai.api-key=<<google-genai-api-key>>
#add model to connect local ollama server
spring.ai.ollama.chat.model=llama3.2:latest
spring.ai.ollama.base-url=http://localhost:11434